"""Long-term memory + retrieval (RAG) for the chatbot.

Two layers:

* **SQLite store** - every session and message is persisted forever and is
  searchable (`search_text`), so the bot remembers across restarts.
* **Semantic retrieval** - messages are embedded and the most relevant past
  messages are pulled back in as context. Embeddings use
  ``sentence-transformers`` when available, otherwise a TF-IDF vectoriser
  (scikit-learn) so retrieval works with zero extra downloads.

Placeholder counts are generated by ``_sql()`` from the column list, so the
number of ``?`` always matches the number of columns.
"""
from __future__ import annotations

import re
import sqlite3
import time
from typing import Optional

from config import DB_PATH

SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions(
    id INTEGER PRIMARY KEY, title TEXT, started REAL);
CREATE TABLE IF NOT EXISTS messages(
    id INTEGER PRIMARY KEY, session_id INT, role TEXT, content TEXT, ts REAL,
    embedding BLOB);
CREATE INDEX IF NOT EXISTS idx_msg_sess ON messages(session_id, id);
CREATE TABLE IF NOT EXISTS facts(
    id INTEGER PRIMARY KEY, session_id INT, key TEXT, value TEXT, ts REAL);
"""


def _sql(table_cols: str) -> str:
    """Build an INSERT with a placeholder per column.

    `table_cols` is like "messages(session_id,role,content,ts,embedding)".
    """
    table, _, cols = table_cols.partition("(")
    cols = cols.rstrip(")")
    n = len([c for c in cols.split(",") if c.strip()])
    marks = "(" + ",".join(["?"] * n) + ")"
    return f"INSERT INTO {table}({cols}) VALUES{marks}"


def get_conn(db_path=None):
    conn = sqlite3.connect(db_path or DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.executescript(SCHEMA)
    _migrate(conn)
    return conn
# Columns added after the first release. `CREATE TABLE IF NOT EXISTS` will not
# alter an existing chat.db, so an older database would be missing these unless
# we add them explicitly.
_MIGRATIONS = {
    "sessions": {"title": "TEXT"},
    "messages": {"embedding": "BLOB"},
}


def _migrate(conn):
    for table, cols in _MIGRATIONS.items():
        existing = {r[1] for r in conn.execute(f"PRAGMA table_info({table})")}
        if not existing:
            continue
        for name, decl in cols.items():
            if name not in existing:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN {name} {decl}")
    conn.commit()


def new_session(conn, title: Optional[str] = None):
    cur = conn.execute(_sql("sessions(title,started)"), (title, time.time()))
    conn.commit()
    return cur.lastrowid


def rename_session(conn, sid, title):
    conn.execute("UPDATE sessions SET title=? WHERE id=?", (title, sid))
    conn.commit()


def add(conn, sid, role, content, embedding: Optional[bytes] = None):
    cur = conn.execute(
        _sql("messages(session_id,role,content,ts,embedding)"),
        (sid, role, content, time.time(), embedding))
    conn.commit()
    return cur.lastrowid


def set_embedding(conn, message_id, blob: bytes):
    conn.execute("UPDATE messages SET embedding=? WHERE id=?", (blob, message_id))
    conn.commit()


def recent(conn, sid, n):
    rows = conn.execute(
        "SELECT role,content FROM messages WHERE session_id=?"
        " ORDER BY id DESC LIMIT ?", (sid, n)).fetchall()[::-1]
    return [dict(r) for r in rows]


def sessions(conn, limit=50):
    rows = conn.execute(
        "SELECT s.id, s.title, s.started, COUNT(m.id) n"
        " FROM sessions s LEFT JOIN messages m ON m.session_id=s.id"
        " GROUP BY s.id ORDER BY s.started DESC LIMIT ?", (limit,)).fetchall()
    return [dict(r) for r in rows]


def search_text(conn, keyword, limit=10, session_id=None):
    """Plain substring search (fast fallback and exact-match lookups)."""
    sql = ("SELECT session_id, role, content, ts FROM messages"
           " WHERE content LIKE ?")
    args = [f"%{keyword}%"]
    if session_id is not None:
        sql += " AND session_id=?"
        args.append(session_id)
    sql += " ORDER BY id DESC LIMIT ?"
    args.append(limit)
    return [dict(r) for r in conn.execute(sql, args).fetchall()]


# --------------------------------------------------------------- embeddings ---
_WORD = re.compile(r"[a-zA-Z0-9']+")

_st_model = None
_st_failed = False


def _tokenize(text: str):
    return _WORD.findall(text.lower())


def _try_sentence_transformer():
    """Load a real embedding model once; return None if unavailable."""
    global _st_model, _st_failed
    if _st_model is not None or _st_failed:
        return _st_model
    try:
        from sentence_transformers import SentenceTransformer
        from config import EMBED_MODEL
        _st_model = SentenceTransformer(EMBED_MODEL)
    except Exception:
        _st_failed = True
        _st_model = None
    return _st_model


class Retriever:
    """Semantic-ish retrieval. Uses the best embedder available and never
    crashes: falls back to TF-IDF cosine similarity, then to substring match.
    """

    def __init__(self, conn):
        self.conn = conn
        self._tfidf = None
        self._matrix = None
        self._ids: list[int] = []
        self._texts: list[str] = []

    # -- index ---------------------------------------------------------------
    def build(self):
        rows = self.conn.execute(
            "SELECT id, content FROM messages WHERE role IN ('user','bot')"
            " ORDER BY id").fetchall()
        self._ids = [r["id"] for r in rows]
        self._texts = [r["content"] for r in rows]
        self._tfidf = None
        if _try_sentence_transformer() is None and self._texts:
            try:
                from sklearn.feature_extraction.text import TfidfVectorizer
                self._tfidf = TfidfVectorizer(tokenizer=_tokenize,
                                              token_pattern=None,
                                              lowercase=False, min_df=1)
                self._matrix = self._tfidf.fit_transform(self._texts)
            except Exception:
                self._tfidf = None
        return self

    # -- query ---------------------------------------------------------------
    def query(self, text: str, top_k=4, exclude_recent_ids=()):
        if not self._texts:
            self.build()
        if not self._texts:
            return []

        st = _try_sentence_transformer()
        if st is not None:
            return self._query_with_st(st, text, top_k, exclude_recent_ids)
        if self._tfidf is not None:
            return self._query_with_tfidf(text, top_k, exclude_recent_ids)
        return [m for m in search_text(self.conn, text[:40], top_k)]

    def _query_with_st(self, st, text, top_k, exclude):
        import numpy as np
        emb = st.encode([text], normalize_embeddings=True)
        mat = st.encode(self._texts, normalize_embeddings=True)
        sims = (mat @ emb.T).ravel()
        order = np.argsort(-sims)
        out = []
        for i in order:
            mid = self._ids[i]
            if mid in exclude:
                continue
            out.append({"content": self._texts[i], "score": float(sims[i]),
                        "message_id": mid})
            if len(out) >= top_k:
                break
        return out

    def _query_with_tfidf(self, text, top_k, exclude):
        from sklearn.metrics.pairwise import cosine_similarity
        vec = self._tfidf.transform([text])
        sims = cosine_similarity(vec, self._matrix).ravel()
        order = sims.argsort()[::-1]
        out = []
        for i in order:
            if sims[i] <= 0:
                continue
            mid = self._ids[i]
            if mid in exclude:
                continue
            out.append({"content": self._texts[i], "score": float(sims[i]),
                        "message_id": mid})
            if len(out) >= top_k:
                break
        return out


# ------------------------------------------------------------ simple facts ----
def remember_fact(conn, sid, key, value):
    conn.execute(_sql("facts(session_id,key,value,ts)"),
                 (sid, key, value, time.time()))
    conn.commit()


def recall_facts(conn, sid=None, limit=20):
    if sid is None:
        rows = conn.execute("SELECT key,value FROM facts ORDER BY id DESC LIMIT ?",
                            (limit,)).fetchall()
    else:
        rows = conn.execute(
            "SELECT key,value FROM facts WHERE session_id=? ORDER BY id DESC LIMIT ?",
            (sid, limit)).fetchall()
    return [dict(r) for r in rows]


def stats(conn):
    s = conn.execute("SELECT COUNT(*) c FROM sessions").fetchone()["c"]
    m = conn.execute("SELECT COUNT(*) c FROM messages").fetchone()["c"]
    f = conn.execute("SELECT COUNT(*) c FROM facts").fetchone()["c"]
    return {"sessions": s, "messages": m, "facts": f}
